# Generated by Django 5.0.6 on 2024-08-27 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbound',
            name='date_received',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='outbound',
            name='date_shipped',
            field=models.DateField(blank=True, null=True),
        ),
    ]
